// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package sqlite

import (
	"context"
	"time"
)

const deleteTokensByUserId = `-- name: DeleteTokensByUserId :exec
DELETE FROM tokens WHERE id IN (
        SELECT token_id FROM users_tokens WHERE user_id = ?
    )
`

// DeleteTokensByUserId
//
//	DELETE FROM tokens WHERE id IN (
//	        SELECT token_id FROM users_tokens WHERE user_id = ?
//	    )
func (q *Queries) DeleteTokensByUserId(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByUserId, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

// DeleteUser
//
//	DELETE FROM users WHERE id = ?
func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const insertToken = `-- name: InsertToken :one
INSERT INTO tokens (jwt_type, jwt, valid, family) VALUES (?, ?, ?, ?) RETURNING id, jwt_type, jwt, valid, family
`

type InsertTokenParams struct {
	JwtType string
	Jwt     string
	Valid   bool
	Family  string
}

// InsertToken
//
//	INSERT INTO tokens (jwt_type, jwt, valid, family) VALUES (?, ?, ?, ?) RETURNING id, jwt_type, jwt, valid, family
func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, insertToken,
		arg.JwtType,
		arg.Jwt,
		arg.Valid,
		arg.Family,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.JwtType,
		&i.Jwt,
		&i.Valid,
		&i.Family,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users ( id, email, username, password_salt, encrypted_password, password_created_at)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, email, username
`

type InsertUserParams struct {
	ID                string
	Email             string
	Username          string
	PasswordSalt      string
	EncryptedPassword string
	PasswordCreatedAt time.Time
}

type InsertUserRow struct {
	ID       string
	Email    string
	Username string
}

// table: users
//
//	INSERT INTO users ( id, email, username, password_salt, encrypted_password, password_created_at)
//	VALUES (?, ?, ?, ?, ?, ?) RETURNING id, email, username
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordSalt,
		arg.EncryptedPassword,
		arg.PasswordCreatedAt,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const insertUsersTokens = `-- name: InsertUsersTokens :exec
INSERT INTO users_tokens (user_id, token_id) VALUES (?, ?)
`

type InsertUsersTokensParams struct {
	UserID  string
	TokenID int64
}

// InsertUsersTokens
//
//	INSERT INTO users_tokens (user_id, token_id) VALUES (?, ?)
func (q *Queries) InsertUsersTokens(ctx context.Context, arg InsertUsersTokensParams) error {
	_, err := q.db.ExecContext(ctx, insertUsersTokens, arg.UserID, arg.TokenID)
	return err
}

const selectTokenFromId = `-- name: SelectTokenFromId :one
SELECT id, jwt_type, jwt, valid, family FROM tokens WHERE id = ?
`

// table: tokens
//
//	SELECT id, jwt_type, jwt, valid, family FROM tokens WHERE id = ?
func (q *Queries) SelectTokenFromId(ctx context.Context, id int64) (Token, error) {
	row := q.db.QueryRowContext(ctx, selectTokenFromId, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.JwtType,
		&i.Jwt,
		&i.Valid,
		&i.Family,
	)
	return i, err
}

const selectTokenFromJwtString = `-- name: SelectTokenFromJwtString :one
SELECT id, jwt_type, jwt, valid, family FROM tokens WHERE jwt = ?
`

// SelectTokenFromJwtString
//
//	SELECT id, jwt_type, jwt, valid, family FROM tokens WHERE jwt = ?
func (q *Queries) SelectTokenFromJwtString(ctx context.Context, jwt string) (Token, error) {
	row := q.db.QueryRowContext(ctx, selectTokenFromJwtString, jwt)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.JwtType,
		&i.Jwt,
		&i.Valid,
		&i.Family,
	)
	return i, err
}

const selectUserByEmail = `-- name: SelectUserByEmail :one
SELECT id, email, username FROM users WHERE email = ?
`

type SelectUserByEmailRow struct {
	ID       string
	Email    string
	Username string
}

// SelectUserByEmail
//
//	SELECT id, email, username FROM users WHERE email = ?
func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (SelectUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, selectUserByEmail, email)
	var i SelectUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const selectUserByEmailWithPassword = `-- name: SelectUserByEmailWithPassword :one
SELECT (id, 
        email,
        username,
        password_salt,
        encrypted_password,
        password_created_at
        ) FROM users WHERE email = ?
`

// SelectUserByEmailWithPassword
//
//	SELECT (id,
//	        email,
//	        username,
//	        password_salt,
//	        encrypted_password,
//	        password_created_at
//	        ) FROM users WHERE email = ?
func (q *Queries) SelectUserByEmailWithPassword(ctx context.Context, email string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, selectUserByEmailWithPassword, email)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const selectUserById = `-- name: SelectUserById :one
SELECT id, email, username FROM users WHERE id = ?
`

type SelectUserByIdRow struct {
	ID       string
	Email    string
	Username string
}

// SelectUserById
//
//	SELECT id, email, username FROM users WHERE id = ?
func (q *Queries) SelectUserById(ctx context.Context, id string) (SelectUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectUserById, id)
	var i SelectUserByIdRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const selectUserByUsername = `-- name: SelectUserByUsername :one
SELECT id, email, username FROM users WHERE username = ?
`

type SelectUserByUsernameRow struct {
	ID       string
	Email    string
	Username string
}

// SelectUserByUsername
//
//	SELECT id, email, username FROM users WHERE username = ?
func (q *Queries) SelectUserByUsername(ctx context.Context, username string) (SelectUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, selectUserByUsername, username)
	var i SelectUserByUsernameRow
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const selectUserByUsernameWithPassword = `-- name: SelectUserByUsernameWithPassword :one
SELECT (id, 
        email,
        username,
        password_salt,
        encrypted_password,
        password_created_at
        ) FROM users WHERE username = ?
`

// SelectUserByUsernameWithPassword
//
//	SELECT (id,
//	        email,
//	        username,
//	        password_salt,
//	        encrypted_password,
//	        password_created_at
//	        ) FROM users WHERE username = ?
func (q *Queries) SelectUserByUsernameWithPassword(ctx context.Context, username string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, selectUserByUsernameWithPassword, username)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const selectUserIdFromToken = `-- name: SelectUserIdFromToken :one
SELECT user_id FROM users_tokens WHERE token_id = ? LIMIT 1
`

// SelectUserIdFromToken
//
//	SELECT user_id FROM users_tokens WHERE token_id = ? LIMIT 1
func (q *Queries) SelectUserIdFromToken(ctx context.Context, tokenID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, selectUserIdFromToken, tokenID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const selectUsersTokens = `-- name: SelectUsersTokens :many
SELECT user_id, token_id FROM users_tokens WHERE user_id = ?
`

// table: users_tokens
//
//	SELECT user_id, token_id FROM users_tokens WHERE user_id = ?
func (q *Queries) SelectUsersTokens(ctx context.Context, userID string) ([]UsersToken, error) {
	rows, err := q.db.QueryContext(ctx, selectUsersTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersToken
	for rows.Next() {
		var i UsersToken
		if err := rows.Scan(&i.UserID, &i.TokenID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenValid = `-- name: UpdateTokenValid :one
UPDATE tokens SET valid = ? WHERE jwt = ? RETURNING id
`

type UpdateTokenValidParams struct {
	Valid bool
	Jwt   string
}

// UpdateTokenValid
//
//	UPDATE tokens SET valid = ? WHERE jwt = ? RETURNING id
func (q *Queries) UpdateTokenValid(ctx context.Context, arg UpdateTokenValidParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateTokenValid, arg.Valid, arg.Jwt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateTokensFamilyInvalid = `-- name: UpdateTokensFamilyInvalid :exec
UPDATE tokens SET valid = FALSE WHERE family = ?
`

// UpdateTokensFamilyInvalid
//
//	UPDATE tokens SET valid = FALSE WHERE family = ?
func (q *Queries) UpdateTokensFamilyInvalid(ctx context.Context, family string) error {
	_, err := q.db.ExecContext(ctx, updateTokensFamilyInvalid, family)
	return err
}

const updateUserTokensToInvalid = `-- name: UpdateUserTokensToInvalid :exec
UPDATE tokens SET valid = FALSE WHERE id IN (
        SELECT token_id FROM users_tokens WHERE user_id = ?
    )
`

// UpdateUserTokensToInvalid
//
//	UPDATE tokens SET valid = FALSE WHERE id IN (
//	        SELECT token_id FROM users_tokens WHERE user_id = ?
//	    )
func (q *Queries) UpdateUserTokensToInvalid(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, updateUserTokensToInvalid, userID)
	return err
}
