// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Protected(username string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Protected Page</title><style>\n\t\t\tbody {\n\t\t\t\tfont-family: Arial, sans-serif;\n\t\t\t\tmax-width: 800px;\n\t\t\t\tmargin: 0 auto;\n\t\t\t\tpadding: 20px;\n\t\t\t\tbackground-color: #f5f5f5;\n\t\t\t}\n\t\t\t.container {\n\t\t\t\tbackground-color: white;\n\t\t\t\tpadding: 30px;\n\t\t\t\tborder-radius: 8px;\n\t\t\t\tbox-shadow: 0 2px 10px rgba(0,0,0,0.1);\n\t\t\t}\n\t\t\t.header {\n\t\t\t\ttext-align: center;\n\t\t\t\tmargin-bottom: 30px;\n\t\t\t}\n\t\t\t.welcome {\n\t\t\t\tcolor: #28a745;\n\t\t\t\tfont-size: 24px;\n\t\t\t\tmargin-bottom: 10px;\n\t\t\t}\n\t\t\t.info {\n\t\t\t\tcolor: #666;\n\t\t\t\tmargin-bottom: 20px;\n\t\t\t}\n\t\t\t.user-info {\n\t\t\t\tbackground-color: #e9ecef;\n\t\t\t\tpadding: 15px;\n\t\t\t\tborder-radius: 5px;\n\t\t\t\tmargin: 20px 0;\n\t\t\t}\n\t\t\t.actions {\n\t\t\t\ttext-align: center;\n\t\t\t\tmargin-top: 30px;\n\t\t\t}\n\t\t\t.btn {\n\t\t\t\tdisplay: inline-block;\n\t\t\t\tpadding: 10px 20px;\n\t\t\t\tmargin: 0 10px;\n\t\t\t\ttext-decoration: none;\n\t\t\t\tborder-radius: 5px;\n\t\t\t\tfont-weight: bold;\n\t\t\t\ttransition: background-color 0.3s;\n\t\t\t}\n\t\t\t.btn-primary {\n\t\t\t\tbackground-color: #007bff;\n\t\t\t\tcolor: white;\n\t\t\t}\n\t\t\t.btn-primary:hover {\n\t\t\t\tbackground-color: #0056b3;\n\t\t\t}\n\t\t\t.btn-secondary {\n\t\t\t\tbackground-color: #6c757d;\n\t\t\t\tcolor: white;\n\t\t\t}\n\t\t\t.btn-secondary:hover {\n\t\t\t\tbackground-color: #545b62;\n\t\t\t}\n\t\t</style></head><body><div class=\"container\"><div class=\"header\"><h1 class=\"welcome\">🔒 Protected Area</h1><p class=\"info\">You have successfully accessed a protected route!</p></div><div class=\"user-info\"><h3>User Information</h3><p><strong>Username:</strong> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `test/app/components/protected.templ`, Line: 81, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</p><p><strong>Status:</strong> Authenticated</p><p><strong>Access Level:</strong> Protected</p></div><div class=\"content\"><h3>Welcome to your protected dashboard!</h3><p>This page is only accessible to authenticated users. Your JWT token has been validated and you have access to protected resources.</p><h4>Available Actions:</h4><ul><li>View your profile information</li><li>Access secured API endpoints</li><li>Manage your account settings</li><li>View protected content</li></ul></div><div class=\"actions\"><a href=\"/\" class=\"btn btn-primary\">Go to Home</a> <a href=\"/auth/signout\" class=\"btn btn-secondary\">Sign Out</a></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
